// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package auto_scaling_group

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/autoscaling"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/autoscaling/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/autoscaling-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AutoScalingGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeAutoScalingGroupsOutput
	resp, err = rm.sdkapi.DescribeAutoScalingGroups(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeAutoScalingGroups", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.AutoScalingGroups {
		if elem.AutoScalingGroupARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.AutoScalingGroupARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AutoScalingGroupName != nil {
			ko.Spec.AutoScalingGroupName = elem.AutoScalingGroupName
		} else {
			ko.Spec.AutoScalingGroupName = nil
		}
		if elem.AvailabilityZoneDistribution != nil {
			f2 := &svcapitypes.AvailabilityZoneDistribution{}
			if elem.AvailabilityZoneDistribution.CapacityDistributionStrategy != "" {
				f2.CapacityDistributionStrategy = aws.String(string(elem.AvailabilityZoneDistribution.CapacityDistributionStrategy))
			}
			ko.Spec.AvailabilityZoneDistribution = f2
		} else {
			ko.Spec.AvailabilityZoneDistribution = nil
		}
		if elem.AvailabilityZoneImpairmentPolicy != nil {
			f3 := &svcapitypes.AvailabilityZoneImpairmentPolicy{}
			if elem.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior != "" {
				f3.ImpairedZoneHealthCheckBehavior = aws.String(string(elem.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior))
			}
			if elem.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled != nil {
				f3.ZonalShiftEnabled = elem.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled
			}
			ko.Spec.AvailabilityZoneImpairmentPolicy = f3
		} else {
			ko.Spec.AvailabilityZoneImpairmentPolicy = nil
		}
		if elem.AvailabilityZones != nil {
			ko.Spec.AvailabilityZones = aws.StringSlice(elem.AvailabilityZones)
		} else {
			ko.Spec.AvailabilityZones = nil
		}
		if elem.CapacityRebalance != nil {
			ko.Spec.CapacityRebalance = elem.CapacityRebalance
		} else {
			ko.Spec.CapacityRebalance = nil
		}
		if elem.CapacityReservationSpecification != nil {
			f6 := &svcapitypes.CapacityReservationSpecification{}
			if elem.CapacityReservationSpecification.CapacityReservationPreference != "" {
				f6.CapacityReservationPreference = aws.String(string(elem.CapacityReservationSpecification.CapacityReservationPreference))
			}
			if elem.CapacityReservationSpecification.CapacityReservationTarget != nil {
				f6f1 := &svcapitypes.CapacityReservationTarget{}
				if elem.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIds != nil {
					f6f1.CapacityReservationIDs = aws.StringSlice(elem.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIds)
				}
				if elem.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArns != nil {
					f6f1.CapacityReservationResourceGroupARNs = aws.StringSlice(elem.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArns)
				}
				f6.CapacityReservationTarget = f6f1
			}
			ko.Spec.CapacityReservationSpecification = f6
		} else {
			ko.Spec.CapacityReservationSpecification = nil
		}
		if elem.Context != nil {
			ko.Spec.Context = elem.Context
		} else {
			ko.Spec.Context = nil
		}
		if elem.DefaultCooldown != nil {
			defaultCooldownCopy := int64(*elem.DefaultCooldown)
			ko.Spec.DefaultCooldown = &defaultCooldownCopy
		} else {
			ko.Spec.DefaultCooldown = nil
		}
		if elem.DefaultInstanceWarmup != nil {
			defaultInstanceWarmupCopy := int64(*elem.DefaultInstanceWarmup)
			ko.Spec.DefaultInstanceWarmup = &defaultInstanceWarmupCopy
		} else {
			ko.Spec.DefaultInstanceWarmup = nil
		}
		if elem.DesiredCapacity != nil {
			desiredCapacityCopy := int64(*elem.DesiredCapacity)
			ko.Spec.DesiredCapacity = &desiredCapacityCopy
		} else {
			ko.Spec.DesiredCapacity = nil
		}
		if elem.DesiredCapacityType != nil {
			ko.Spec.DesiredCapacityType = elem.DesiredCapacityType
		} else {
			ko.Spec.DesiredCapacityType = nil
		}
		if elem.HealthCheckGracePeriod != nil {
			healthCheckGracePeriodCopy := int64(*elem.HealthCheckGracePeriod)
			ko.Spec.HealthCheckGracePeriod = &healthCheckGracePeriodCopy
		} else {
			ko.Spec.HealthCheckGracePeriod = nil
		}
		if elem.HealthCheckType != nil {
			ko.Spec.HealthCheckType = elem.HealthCheckType
		} else {
			ko.Spec.HealthCheckType = nil
		}
		if elem.InstanceMaintenancePolicy != nil {
			f16 := &svcapitypes.InstanceMaintenancePolicy{}
			if elem.InstanceMaintenancePolicy.MaxHealthyPercentage != nil {
				maxHealthyPercentageCopy := int64(*elem.InstanceMaintenancePolicy.MaxHealthyPercentage)
				f16.MaxHealthyPercentage = &maxHealthyPercentageCopy
			}
			if elem.InstanceMaintenancePolicy.MinHealthyPercentage != nil {
				minHealthyPercentageCopy := int64(*elem.InstanceMaintenancePolicy.MinHealthyPercentage)
				f16.MinHealthyPercentage = &minHealthyPercentageCopy
			}
			ko.Spec.InstanceMaintenancePolicy = f16
		} else {
			ko.Spec.InstanceMaintenancePolicy = nil
		}
		if elem.LaunchConfigurationName != nil {
			ko.Spec.LaunchConfigurationName = elem.LaunchConfigurationName
		} else {
			ko.Spec.LaunchConfigurationName = nil
		}
		if elem.LaunchTemplate != nil {
			f19 := &svcapitypes.LaunchTemplateSpecification{}
			if elem.LaunchTemplate.LaunchTemplateId != nil {
				f19.LaunchTemplateID = elem.LaunchTemplate.LaunchTemplateId
			}
			if elem.LaunchTemplate.LaunchTemplateName != nil {
				f19.LaunchTemplateName = elem.LaunchTemplate.LaunchTemplateName
			}
			if elem.LaunchTemplate.Version != nil {
				f19.Version = elem.LaunchTemplate.Version
			}
			ko.Spec.LaunchTemplate = f19
		} else {
			ko.Spec.LaunchTemplate = nil
		}
		if elem.LoadBalancerNames != nil {
			ko.Spec.LoadBalancerNames = aws.StringSlice(elem.LoadBalancerNames)
		} else {
			ko.Spec.LoadBalancerNames = nil
		}
		if elem.MaxInstanceLifetime != nil {
			maxInstanceLifetimeCopy := int64(*elem.MaxInstanceLifetime)
			ko.Spec.MaxInstanceLifetime = &maxInstanceLifetimeCopy
		} else {
			ko.Spec.MaxInstanceLifetime = nil
		}
		if elem.MaxSize != nil {
			maxSizeCopy := int64(*elem.MaxSize)
			ko.Spec.MaxSize = &maxSizeCopy
		} else {
			ko.Spec.MaxSize = nil
		}
		if elem.MinSize != nil {
			minSizeCopy := int64(*elem.MinSize)
			ko.Spec.MinSize = &minSizeCopy
		} else {
			ko.Spec.MinSize = nil
		}
		if elem.MixedInstancesPolicy != nil {
			f24 := &svcapitypes.MixedInstancesPolicy{}
			if elem.MixedInstancesPolicy.InstancesDistribution != nil {
				f24f0 := &svcapitypes.InstancesDistribution{}
				if elem.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
					f24f0.OnDemandAllocationStrategy = elem.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
					onDemandBaseCapacityCopy := int64(*elem.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity)
					f24f0.OnDemandBaseCapacity = &onDemandBaseCapacityCopy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
					onDemandPercentageAboveBaseCapacityCopy := int64(*elem.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity)
					f24f0.OnDemandPercentageAboveBaseCapacity = &onDemandPercentageAboveBaseCapacityCopy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
					f24f0.SpotAllocationStrategy = elem.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
					spotInstancePoolsCopy := int64(*elem.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools)
					f24f0.SpotInstancePools = &spotInstancePoolsCopy
				}
				if elem.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
					f24f0.SpotMaxPrice = elem.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice
				}
				f24.InstancesDistribution = f24f0
			}
			if elem.MixedInstancesPolicy.LaunchTemplate != nil {
				f24f1 := &svcapitypes.LaunchTemplate{}
				if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
					f24f1f0 := &svcapitypes.LaunchTemplateSpecification{}
					if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateId != nil {
						f24f1f0.LaunchTemplateID = elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateId
					}
					if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
						f24f1f0.LaunchTemplateName = elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName
					}
					if elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
						f24f1f0.Version = elem.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version
					}
					f24f1.LaunchTemplateSpecification = f24f1f0
				}
				if elem.MixedInstancesPolicy.LaunchTemplate.Overrides != nil {
					f24f1f1 := []*svcapitypes.LaunchTemplateOverrides{}
					for _, f24f1f1iter := range elem.MixedInstancesPolicy.LaunchTemplate.Overrides {
						f24f1f1elem := &svcapitypes.LaunchTemplateOverrides{}
						if f24f1f1iter.InstanceRequirements != nil {
							f24f1f1elemf0 := &svcapitypes.InstanceRequirements{}
							if f24f1f1iter.InstanceRequirements.AcceleratorCount != nil {
								f24f1f1elemf0f0 := &svcapitypes.AcceleratorCountRequest{}
								if f24f1f1iter.InstanceRequirements.AcceleratorCount.Max != nil {
									maxCopy := int64(*f24f1f1iter.InstanceRequirements.AcceleratorCount.Max)
									f24f1f1elemf0f0.Max = &maxCopy
								}
								if f24f1f1iter.InstanceRequirements.AcceleratorCount.Min != nil {
									minCopy := int64(*f24f1f1iter.InstanceRequirements.AcceleratorCount.Min)
									f24f1f1elemf0f0.Min = &minCopy
								}
								f24f1f1elemf0.AcceleratorCount = f24f1f1elemf0f0
							}
							if f24f1f1iter.InstanceRequirements.AcceleratorManufacturers != nil {
								f24f1f1elemf0f1 := []*string{}
								for _, f24f1f1elemf0f1iter := range f24f1f1iter.InstanceRequirements.AcceleratorManufacturers {
									var f24f1f1elemf0f1elem *string
									f24f1f1elemf0f1elem = aws.String(string(f24f1f1elemf0f1iter))
									f24f1f1elemf0f1 = append(f24f1f1elemf0f1, f24f1f1elemf0f1elem)
								}
								f24f1f1elemf0.AcceleratorManufacturers = f24f1f1elemf0f1
							}
							if f24f1f1iter.InstanceRequirements.AcceleratorNames != nil {
								f24f1f1elemf0f2 := []*string{}
								for _, f24f1f1elemf0f2iter := range f24f1f1iter.InstanceRequirements.AcceleratorNames {
									var f24f1f1elemf0f2elem *string
									f24f1f1elemf0f2elem = aws.String(string(f24f1f1elemf0f2iter))
									f24f1f1elemf0f2 = append(f24f1f1elemf0f2, f24f1f1elemf0f2elem)
								}
								f24f1f1elemf0.AcceleratorNames = f24f1f1elemf0f2
							}
							if f24f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
								f24f1f1elemf0f3 := &svcapitypes.AcceleratorTotalMemoryMiBRequest{}
								if f24f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
									maxCopy := int64(*f24f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max)
									f24f1f1elemf0f3.Max = &maxCopy
								}
								if f24f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
									minCopy := int64(*f24f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min)
									f24f1f1elemf0f3.Min = &minCopy
								}
								f24f1f1elemf0.AcceleratorTotalMemoryMiB = f24f1f1elemf0f3
							}
							if f24f1f1iter.InstanceRequirements.AcceleratorTypes != nil {
								f24f1f1elemf0f4 := []*string{}
								for _, f24f1f1elemf0f4iter := range f24f1f1iter.InstanceRequirements.AcceleratorTypes {
									var f24f1f1elemf0f4elem *string
									f24f1f1elemf0f4elem = aws.String(string(f24f1f1elemf0f4iter))
									f24f1f1elemf0f4 = append(f24f1f1elemf0f4, f24f1f1elemf0f4elem)
								}
								f24f1f1elemf0.AcceleratorTypes = f24f1f1elemf0f4
							}
							if f24f1f1iter.InstanceRequirements.AllowedInstanceTypes != nil {
								f24f1f1elemf0.AllowedInstanceTypes = aws.StringSlice(f24f1f1iter.InstanceRequirements.AllowedInstanceTypes)
							}
							if f24f1f1iter.InstanceRequirements.BareMetal != "" {
								f24f1f1elemf0.BareMetal = aws.String(string(f24f1f1iter.InstanceRequirements.BareMetal))
							}
							if f24f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps != nil {
								f24f1f1elemf0f7 := &svcapitypes.BaselineEBSBandwidthMbpsRequest{}
								if f24f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Max != nil {
									maxCopy := int64(*f24f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Max)
									f24f1f1elemf0f7.Max = &maxCopy
								}
								if f24f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Min != nil {
									minCopy := int64(*f24f1f1iter.InstanceRequirements.BaselineEbsBandwidthMbps.Min)
									f24f1f1elemf0f7.Min = &minCopy
								}
								f24f1f1elemf0.BaselineEBSBandwidthMbps = f24f1f1elemf0f7
							}
							if f24f1f1iter.InstanceRequirements.BaselinePerformanceFactors != nil {
								f24f1f1elemf0f8 := &svcapitypes.BaselinePerformanceFactorsRequest{}
								if f24f1f1iter.InstanceRequirements.BaselinePerformanceFactors.Cpu != nil {
									f24f1f1elemf0f8f0 := &svcapitypes.CPUPerformanceFactorRequest{}
									if f24f1f1iter.InstanceRequirements.BaselinePerformanceFactors.Cpu.References != nil {
										f24f1f1elemf0f8f0f0 := []*svcapitypes.PerformanceFactorReferenceRequest{}
										for _, f24f1f1elemf0f8f0f0iter := range f24f1f1iter.InstanceRequirements.BaselinePerformanceFactors.Cpu.References {
											f24f1f1elemf0f8f0f0elem := &svcapitypes.PerformanceFactorReferenceRequest{}
											if f24f1f1elemf0f8f0f0iter.InstanceFamily != nil {
												f24f1f1elemf0f8f0f0elem.InstanceFamily = f24f1f1elemf0f8f0f0iter.InstanceFamily
											}
											f24f1f1elemf0f8f0f0 = append(f24f1f1elemf0f8f0f0, f24f1f1elemf0f8f0f0elem)
										}
										f24f1f1elemf0f8f0.References = f24f1f1elemf0f8f0f0
									}
									f24f1f1elemf0f8.CPU = f24f1f1elemf0f8f0
								}
								f24f1f1elemf0.BaselinePerformanceFactors = f24f1f1elemf0f8
							}
							if f24f1f1iter.InstanceRequirements.BurstablePerformance != "" {
								f24f1f1elemf0.BurstablePerformance = aws.String(string(f24f1f1iter.InstanceRequirements.BurstablePerformance))
							}
							if f24f1f1iter.InstanceRequirements.CpuManufacturers != nil {
								f24f1f1elemf0f10 := []*string{}
								for _, f24f1f1elemf0f10iter := range f24f1f1iter.InstanceRequirements.CpuManufacturers {
									var f24f1f1elemf0f10elem *string
									f24f1f1elemf0f10elem = aws.String(string(f24f1f1elemf0f10iter))
									f24f1f1elemf0f10 = append(f24f1f1elemf0f10, f24f1f1elemf0f10elem)
								}
								f24f1f1elemf0.CPUManufacturers = f24f1f1elemf0f10
							}
							if f24f1f1iter.InstanceRequirements.ExcludedInstanceTypes != nil {
								f24f1f1elemf0.ExcludedInstanceTypes = aws.StringSlice(f24f1f1iter.InstanceRequirements.ExcludedInstanceTypes)
							}
							if f24f1f1iter.InstanceRequirements.InstanceGenerations != nil {
								f24f1f1elemf0f12 := []*string{}
								for _, f24f1f1elemf0f12iter := range f24f1f1iter.InstanceRequirements.InstanceGenerations {
									var f24f1f1elemf0f12elem *string
									f24f1f1elemf0f12elem = aws.String(string(f24f1f1elemf0f12iter))
									f24f1f1elemf0f12 = append(f24f1f1elemf0f12, f24f1f1elemf0f12elem)
								}
								f24f1f1elemf0.InstanceGenerations = f24f1f1elemf0f12
							}
							if f24f1f1iter.InstanceRequirements.LocalStorage != "" {
								f24f1f1elemf0.LocalStorage = aws.String(string(f24f1f1iter.InstanceRequirements.LocalStorage))
							}
							if f24f1f1iter.InstanceRequirements.LocalStorageTypes != nil {
								f24f1f1elemf0f14 := []*string{}
								for _, f24f1f1elemf0f14iter := range f24f1f1iter.InstanceRequirements.LocalStorageTypes {
									var f24f1f1elemf0f14elem *string
									f24f1f1elemf0f14elem = aws.String(string(f24f1f1elemf0f14iter))
									f24f1f1elemf0f14 = append(f24f1f1elemf0f14, f24f1f1elemf0f14elem)
								}
								f24f1f1elemf0.LocalStorageTypes = f24f1f1elemf0f14
							}
							if f24f1f1iter.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice != nil {
								maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy := int64(*f24f1f1iter.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice)
								f24f1f1elemf0.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice = &maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy
							}
							if f24f1f1iter.InstanceRequirements.MemoryGiBPerVCpu != nil {
								f24f1f1elemf0f16 := &svcapitypes.MemoryGiBPerVCPURequest{}
								if f24f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Max != nil {
									f24f1f1elemf0f16.Max = f24f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Max
								}
								if f24f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Min != nil {
									f24f1f1elemf0f16.Min = f24f1f1iter.InstanceRequirements.MemoryGiBPerVCpu.Min
								}
								f24f1f1elemf0.MemoryGiBPerVCPU = f24f1f1elemf0f16
							}
							if f24f1f1iter.InstanceRequirements.MemoryMiB != nil {
								f24f1f1elemf0f17 := &svcapitypes.MemoryMiBRequest{}
								if f24f1f1iter.InstanceRequirements.MemoryMiB.Max != nil {
									maxCopy := int64(*f24f1f1iter.InstanceRequirements.MemoryMiB.Max)
									f24f1f1elemf0f17.Max = &maxCopy
								}
								if f24f1f1iter.InstanceRequirements.MemoryMiB.Min != nil {
									minCopy := int64(*f24f1f1iter.InstanceRequirements.MemoryMiB.Min)
									f24f1f1elemf0f17.Min = &minCopy
								}
								f24f1f1elemf0.MemoryMiB = f24f1f1elemf0f17
							}
							if f24f1f1iter.InstanceRequirements.NetworkBandwidthGbps != nil {
								f24f1f1elemf0f18 := &svcapitypes.NetworkBandwidthGbpsRequest{}
								if f24f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Max != nil {
									f24f1f1elemf0f18.Max = f24f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Max
								}
								if f24f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Min != nil {
									f24f1f1elemf0f18.Min = f24f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Min
								}
								f24f1f1elemf0.NetworkBandwidthGbps = f24f1f1elemf0f18
							}
							if f24f1f1iter.InstanceRequirements.NetworkInterfaceCount != nil {
								f24f1f1elemf0f19 := &svcapitypes.NetworkInterfaceCountRequest{}
								if f24f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max != nil {
									maxCopy := int64(*f24f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max)
									f24f1f1elemf0f19.Max = &maxCopy
								}
								if f24f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min != nil {
									minCopy := int64(*f24f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min)
									f24f1f1elemf0f19.Min = &minCopy
								}
								f24f1f1elemf0.NetworkInterfaceCount = f24f1f1elemf0f19
							}
							if f24f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
								onDemandMaxPricePercentageOverLowestPriceCopy := int64(*f24f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice)
								f24f1f1elemf0.OnDemandMaxPricePercentageOverLowestPrice = &onDemandMaxPricePercentageOverLowestPriceCopy
							}
							if f24f1f1iter.InstanceRequirements.RequireHibernateSupport != nil {
								f24f1f1elemf0.RequireHibernateSupport = f24f1f1iter.InstanceRequirements.RequireHibernateSupport
							}
							if f24f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
								spotMaxPricePercentageOverLowestPriceCopy := int64(*f24f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice)
								f24f1f1elemf0.SpotMaxPricePercentageOverLowestPrice = &spotMaxPricePercentageOverLowestPriceCopy
							}
							if f24f1f1iter.InstanceRequirements.TotalLocalStorageGB != nil {
								f24f1f1elemf0f23 := &svcapitypes.TotalLocalStorageGBRequest{}
								if f24f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max != nil {
									f24f1f1elemf0f23.Max = f24f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max
								}
								if f24f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min != nil {
									f24f1f1elemf0f23.Min = f24f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min
								}
								f24f1f1elemf0.TotalLocalStorageGB = f24f1f1elemf0f23
							}
							if f24f1f1iter.InstanceRequirements.VCpuCount != nil {
								f24f1f1elemf0f24 := &svcapitypes.VCPUCountRequest{}
								if f24f1f1iter.InstanceRequirements.VCpuCount.Max != nil {
									maxCopy := int64(*f24f1f1iter.InstanceRequirements.VCpuCount.Max)
									f24f1f1elemf0f24.Max = &maxCopy
								}
								if f24f1f1iter.InstanceRequirements.VCpuCount.Min != nil {
									minCopy := int64(*f24f1f1iter.InstanceRequirements.VCpuCount.Min)
									f24f1f1elemf0f24.Min = &minCopy
								}
								f24f1f1elemf0.VCPUCount = f24f1f1elemf0f24
							}
							f24f1f1elem.InstanceRequirements = f24f1f1elemf0
						}
						if f24f1f1iter.InstanceType != nil {
							f24f1f1elem.InstanceType = f24f1f1iter.InstanceType
						}
						if f24f1f1iter.LaunchTemplateSpecification != nil {
							f24f1f1elemf2 := &svcapitypes.LaunchTemplateSpecification{}
							if f24f1f1iter.LaunchTemplateSpecification.LaunchTemplateId != nil {
								f24f1f1elemf2.LaunchTemplateID = f24f1f1iter.LaunchTemplateSpecification.LaunchTemplateId
							}
							if f24f1f1iter.LaunchTemplateSpecification.LaunchTemplateName != nil {
								f24f1f1elemf2.LaunchTemplateName = f24f1f1iter.LaunchTemplateSpecification.LaunchTemplateName
							}
							if f24f1f1iter.LaunchTemplateSpecification.Version != nil {
								f24f1f1elemf2.Version = f24f1f1iter.LaunchTemplateSpecification.Version
							}
							f24f1f1elem.LaunchTemplateSpecification = f24f1f1elemf2
						}
						if f24f1f1iter.WeightedCapacity != nil {
							f24f1f1elem.WeightedCapacity = f24f1f1iter.WeightedCapacity
						}
						f24f1f1 = append(f24f1f1, f24f1f1elem)
					}
					f24f1.Overrides = f24f1f1
				}
				f24.LaunchTemplate = f24f1
			}
			ko.Spec.MixedInstancesPolicy = f24
		} else {
			ko.Spec.MixedInstancesPolicy = nil
		}
		if elem.NewInstancesProtectedFromScaleIn != nil {
			ko.Spec.NewInstancesProtectedFromScaleIn = elem.NewInstancesProtectedFromScaleIn
		} else {
			ko.Spec.NewInstancesProtectedFromScaleIn = nil
		}
		if elem.PlacementGroup != nil {
			ko.Spec.PlacementGroup = elem.PlacementGroup
		} else {
			ko.Spec.PlacementGroup = nil
		}
		if elem.ServiceLinkedRoleARN != nil {
			ko.Spec.ServiceLinkedRoleARN = elem.ServiceLinkedRoleARN
		} else {
			ko.Spec.ServiceLinkedRoleARN = nil
		}
		if elem.Tags != nil {
			f31 := []*svcapitypes.Tag{}
			for _, f31iter := range elem.Tags {
				f31elem := &svcapitypes.Tag{}
				if f31iter.Key != nil {
					f31elem.Key = f31iter.Key
				}
				if f31iter.PropagateAtLaunch != nil {
					f31elem.PropagateAtLaunch = f31iter.PropagateAtLaunch
				}
				if f31iter.ResourceId != nil {
					f31elem.ResourceID = f31iter.ResourceId
				}
				if f31iter.ResourceType != nil {
					f31elem.ResourceType = f31iter.ResourceType
				}
				if f31iter.Value != nil {
					f31elem.Value = f31iter.Value
				}
				f31 = append(f31, f31elem)
			}
			ko.Spec.Tags = f31
		} else {
			ko.Spec.Tags = nil
		}
		if elem.TargetGroupARNs != nil {
			ko.Spec.TargetGroupARNs = aws.StringSlice(elem.TargetGroupARNs)
		} else {
			ko.Spec.TargetGroupARNs = nil
		}
		if elem.TerminationPolicies != nil {
			ko.Spec.TerminationPolicies = aws.StringSlice(elem.TerminationPolicies)
		} else {
			ko.Spec.TerminationPolicies = nil
		}
		if elem.TrafficSources != nil {
			f34 := []*svcapitypes.TrafficSourceIdentifier{}
			for _, f34iter := range elem.TrafficSources {
				f34elem := &svcapitypes.TrafficSourceIdentifier{}
				if f34iter.Identifier != nil {
					f34elem.Identifier = f34iter.Identifier
				}
				if f34iter.Type != nil {
					f34elem.Type = f34iter.Type
				}
				f34 = append(f34, f34elem)
			}
			ko.Spec.TrafficSources = f34
		} else {
			ko.Spec.TrafficSources = nil
		}
		if elem.VPCZoneIdentifier != nil {
			ko.Spec.VPCZoneIdentifier = elem.VPCZoneIdentifier
		} else {
			ko.Spec.VPCZoneIdentifier = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.AutoScalingGroupName == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeAutoScalingGroupsInput, error) {
	res := &svcsdk.DescribeAutoScalingGroupsInput{}

	if r.ko.Spec.AutoScalingGroupName != nil {
		f0 := []string{}
		f0 = append(f0, *r.ko.Spec.AutoScalingGroupName)
		res.AutoScalingGroupNames = f0
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAutoScalingGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAutoScalingGroup(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAutoScalingGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	if ko.Spec.Tags != nil {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAutoScalingGroupInput, error) {
	res := &svcsdk.CreateAutoScalingGroupInput{}

	if r.ko.Spec.AutoScalingGroupName != nil {
		res.AutoScalingGroupName = r.ko.Spec.AutoScalingGroupName
	}
	if r.ko.Spec.AvailabilityZoneDistribution != nil {
		f1 := &svcsdktypes.AvailabilityZoneDistribution{}
		if r.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy != nil {
			f1.CapacityDistributionStrategy = svcsdktypes.CapacityDistributionStrategy(*r.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy)
		}
		res.AvailabilityZoneDistribution = f1
	}
	if r.ko.Spec.AvailabilityZoneImpairmentPolicy != nil {
		f2 := &svcsdktypes.AvailabilityZoneImpairmentPolicy{}
		if r.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior != nil {
			f2.ImpairedZoneHealthCheckBehavior = svcsdktypes.ImpairedZoneHealthCheckBehavior(*r.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior)
		}
		if r.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled != nil {
			f2.ZonalShiftEnabled = r.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled
		}
		res.AvailabilityZoneImpairmentPolicy = f2
	}
	if r.ko.Spec.AvailabilityZones != nil {
		res.AvailabilityZones = aws.ToStringSlice(r.ko.Spec.AvailabilityZones)
	}
	if r.ko.Spec.CapacityRebalance != nil {
		res.CapacityRebalance = r.ko.Spec.CapacityRebalance
	}
	if r.ko.Spec.CapacityReservationSpecification != nil {
		f5 := &svcsdktypes.CapacityReservationSpecification{}
		if r.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference != nil {
			f5.CapacityReservationPreference = svcsdktypes.CapacityReservationPreference(*r.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference)
		}
		if r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget != nil {
			f5f1 := &svcsdktypes.CapacityReservationTarget{}
			if r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs != nil {
				f5f1.CapacityReservationIds = aws.ToStringSlice(r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs)
			}
			if r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs != nil {
				f5f1.CapacityReservationResourceGroupArns = aws.ToStringSlice(r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs)
			}
			f5.CapacityReservationTarget = f5f1
		}
		res.CapacityReservationSpecification = f5
	}
	if r.ko.Spec.Context != nil {
		res.Context = r.ko.Spec.Context
	}
	if r.ko.Spec.DefaultCooldown != nil {
		defaultCooldownCopy0 := *r.ko.Spec.DefaultCooldown
		if defaultCooldownCopy0 > math.MaxInt32 || defaultCooldownCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DefaultCooldown is of type int32")
		}
		defaultCooldownCopy := int32(defaultCooldownCopy0)
		res.DefaultCooldown = &defaultCooldownCopy
	}
	if r.ko.Spec.DefaultInstanceWarmup != nil {
		defaultInstanceWarmupCopy0 := *r.ko.Spec.DefaultInstanceWarmup
		if defaultInstanceWarmupCopy0 > math.MaxInt32 || defaultInstanceWarmupCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DefaultInstanceWarmup is of type int32")
		}
		defaultInstanceWarmupCopy := int32(defaultInstanceWarmupCopy0)
		res.DefaultInstanceWarmup = &defaultInstanceWarmupCopy
	}
	if r.ko.Spec.DesiredCapacity != nil {
		desiredCapacityCopy0 := *r.ko.Spec.DesiredCapacity
		if desiredCapacityCopy0 > math.MaxInt32 || desiredCapacityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DesiredCapacity is of type int32")
		}
		desiredCapacityCopy := int32(desiredCapacityCopy0)
		res.DesiredCapacity = &desiredCapacityCopy
	}
	if r.ko.Spec.DesiredCapacityType != nil {
		res.DesiredCapacityType = r.ko.Spec.DesiredCapacityType
	}
	if r.ko.Spec.HealthCheckGracePeriod != nil {
		healthCheckGracePeriodCopy0 := *r.ko.Spec.HealthCheckGracePeriod
		if healthCheckGracePeriodCopy0 > math.MaxInt32 || healthCheckGracePeriodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field HealthCheckGracePeriod is of type int32")
		}
		healthCheckGracePeriodCopy := int32(healthCheckGracePeriodCopy0)
		res.HealthCheckGracePeriod = &healthCheckGracePeriodCopy
	}
	if r.ko.Spec.HealthCheckType != nil {
		res.HealthCheckType = r.ko.Spec.HealthCheckType
	}
	if r.ko.Spec.InstanceID != nil {
		res.InstanceId = r.ko.Spec.InstanceID
	}
	if r.ko.Spec.InstanceMaintenancePolicy != nil {
		f14 := &svcsdktypes.InstanceMaintenancePolicy{}
		if r.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage != nil {
			maxHealthyPercentageCopy0 := *r.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage
			if maxHealthyPercentageCopy0 > math.MaxInt32 || maxHealthyPercentageCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field MaxHealthyPercentage is of type int32")
			}
			maxHealthyPercentageCopy := int32(maxHealthyPercentageCopy0)
			f14.MaxHealthyPercentage = &maxHealthyPercentageCopy
		}
		if r.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage != nil {
			minHealthyPercentageCopy0 := *r.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage
			if minHealthyPercentageCopy0 > math.MaxInt32 || minHealthyPercentageCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field MinHealthyPercentage is of type int32")
			}
			minHealthyPercentageCopy := int32(minHealthyPercentageCopy0)
			f14.MinHealthyPercentage = &minHealthyPercentageCopy
		}
		res.InstanceMaintenancePolicy = f14
	}
	if r.ko.Spec.LaunchConfigurationName != nil {
		res.LaunchConfigurationName = r.ko.Spec.LaunchConfigurationName
	}
	if r.ko.Spec.LaunchTemplate != nil {
		f16 := &svcsdktypes.LaunchTemplateSpecification{}
		if r.ko.Spec.LaunchTemplate.LaunchTemplateID != nil {
			f16.LaunchTemplateId = r.ko.Spec.LaunchTemplate.LaunchTemplateID
		}
		if r.ko.Spec.LaunchTemplate.LaunchTemplateName != nil {
			f16.LaunchTemplateName = r.ko.Spec.LaunchTemplate.LaunchTemplateName
		}
		if r.ko.Spec.LaunchTemplate.Version != nil {
			f16.Version = r.ko.Spec.LaunchTemplate.Version
		}
		res.LaunchTemplate = f16
	}
	if r.ko.Spec.LifecycleHookSpecificationList != nil {
		f17 := []svcsdktypes.LifecycleHookSpecification{}
		for _, f17iter := range r.ko.Spec.LifecycleHookSpecificationList {
			f17elem := &svcsdktypes.LifecycleHookSpecification{}
			if f17iter.DefaultResult != nil {
				f17elem.DefaultResult = f17iter.DefaultResult
			}
			if f17iter.HeartbeatTimeout != nil {
				heartbeatTimeoutCopy0 := *f17iter.HeartbeatTimeout
				if heartbeatTimeoutCopy0 > math.MaxInt32 || heartbeatTimeoutCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field HeartbeatTimeout is of type int32")
				}
				heartbeatTimeoutCopy := int32(heartbeatTimeoutCopy0)
				f17elem.HeartbeatTimeout = &heartbeatTimeoutCopy
			}
			if f17iter.LifecycleHookName != nil {
				f17elem.LifecycleHookName = f17iter.LifecycleHookName
			}
			if f17iter.LifecycleTransition != nil {
				f17elem.LifecycleTransition = f17iter.LifecycleTransition
			}
			if f17iter.NotificationMetadata != nil {
				f17elem.NotificationMetadata = f17iter.NotificationMetadata
			}
			if f17iter.NotificationTargetARN != nil {
				f17elem.NotificationTargetARN = f17iter.NotificationTargetARN
			}
			if f17iter.RoleARN != nil {
				f17elem.RoleARN = f17iter.RoleARN
			}
			f17 = append(f17, *f17elem)
		}
		res.LifecycleHookSpecificationList = f17
	}
	if r.ko.Spec.LoadBalancerNames != nil {
		res.LoadBalancerNames = aws.ToStringSlice(r.ko.Spec.LoadBalancerNames)
	}
	if r.ko.Spec.MaxInstanceLifetime != nil {
		maxInstanceLifetimeCopy0 := *r.ko.Spec.MaxInstanceLifetime
		if maxInstanceLifetimeCopy0 > math.MaxInt32 || maxInstanceLifetimeCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxInstanceLifetime is of type int32")
		}
		maxInstanceLifetimeCopy := int32(maxInstanceLifetimeCopy0)
		res.MaxInstanceLifetime = &maxInstanceLifetimeCopy
	}
	if r.ko.Spec.MaxSize != nil {
		maxSizeCopy0 := *r.ko.Spec.MaxSize
		if maxSizeCopy0 > math.MaxInt32 || maxSizeCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxSize is of type int32")
		}
		maxSizeCopy := int32(maxSizeCopy0)
		res.MaxSize = &maxSizeCopy
	}
	if r.ko.Spec.MinSize != nil {
		minSizeCopy0 := *r.ko.Spec.MinSize
		if minSizeCopy0 > math.MaxInt32 || minSizeCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MinSize is of type int32")
		}
		minSizeCopy := int32(minSizeCopy0)
		res.MinSize = &minSizeCopy
	}
	if r.ko.Spec.MixedInstancesPolicy != nil {
		f22 := &svcsdktypes.MixedInstancesPolicy{}
		if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution != nil {
			f22f0 := &svcsdktypes.InstancesDistribution{}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
				f22f0.OnDemandAllocationStrategy = r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
				onDemandBaseCapacityCopy0 := *r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity
				if onDemandBaseCapacityCopy0 > math.MaxInt32 || onDemandBaseCapacityCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field OnDemandBaseCapacity is of type int32")
				}
				onDemandBaseCapacityCopy := int32(onDemandBaseCapacityCopy0)
				f22f0.OnDemandBaseCapacity = &onDemandBaseCapacityCopy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
				onDemandPercentageAboveBaseCapacityCopy0 := *r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity
				if onDemandPercentageAboveBaseCapacityCopy0 > math.MaxInt32 || onDemandPercentageAboveBaseCapacityCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field OnDemandPercentageAboveBaseCapacity is of type int32")
				}
				onDemandPercentageAboveBaseCapacityCopy := int32(onDemandPercentageAboveBaseCapacityCopy0)
				f22f0.OnDemandPercentageAboveBaseCapacity = &onDemandPercentageAboveBaseCapacityCopy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
				f22f0.SpotAllocationStrategy = r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
				spotInstancePoolsCopy0 := *r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools
				if spotInstancePoolsCopy0 > math.MaxInt32 || spotInstancePoolsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field SpotInstancePools is of type int32")
				}
				spotInstancePoolsCopy := int32(spotInstancePoolsCopy0)
				f22f0.SpotInstancePools = &spotInstancePoolsCopy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
				f22f0.SpotMaxPrice = r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice
			}
			f22.InstancesDistribution = f22f0
		}
		if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil {
			f22f1 := &svcsdktypes.LaunchTemplate{}
			if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				f22f1f0 := &svcsdktypes.LaunchTemplateSpecification{}
				if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID != nil {
					f22f1f0.LaunchTemplateId = r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID
				}
				if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
					f22f1f0.LaunchTemplateName = r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName
				}
				if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
					f22f1f0.Version = r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version
				}
				f22f1.LaunchTemplateSpecification = f22f1f0
			}
			if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides != nil {
				f22f1f1 := []svcsdktypes.LaunchTemplateOverrides{}
				for _, f22f1f1iter := range r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides {
					f22f1f1elem := &svcsdktypes.LaunchTemplateOverrides{}
					if f22f1f1iter.InstanceRequirements != nil {
						f22f1f1elemf0 := &svcsdktypes.InstanceRequirements{}
						if f22f1f1iter.InstanceRequirements.AcceleratorCount != nil {
							f22f1f1elemf0f0 := &svcsdktypes.AcceleratorCountRequest{}
							if f22f1f1iter.InstanceRequirements.AcceleratorCount.Max != nil {
								maxCopy0 := *f22f1f1iter.InstanceRequirements.AcceleratorCount.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f22f1f1elemf0f0.Max = &maxCopy
							}
							if f22f1f1iter.InstanceRequirements.AcceleratorCount.Min != nil {
								minCopy0 := *f22f1f1iter.InstanceRequirements.AcceleratorCount.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f22f1f1elemf0f0.Min = &minCopy
							}
							f22f1f1elemf0.AcceleratorCount = f22f1f1elemf0f0
						}
						if f22f1f1iter.InstanceRequirements.AcceleratorManufacturers != nil {
							f22f1f1elemf0f1 := []svcsdktypes.AcceleratorManufacturer{}
							for _, f22f1f1elemf0f1iter := range f22f1f1iter.InstanceRequirements.AcceleratorManufacturers {
								var f22f1f1elemf0f1elem string
								f22f1f1elemf0f1elem = string(*f22f1f1elemf0f1iter)
								f22f1f1elemf0f1 = append(f22f1f1elemf0f1, svcsdktypes.AcceleratorManufacturer(f22f1f1elemf0f1elem))
							}
							f22f1f1elemf0.AcceleratorManufacturers = f22f1f1elemf0f1
						}
						if f22f1f1iter.InstanceRequirements.AcceleratorNames != nil {
							f22f1f1elemf0f2 := []svcsdktypes.AcceleratorName{}
							for _, f22f1f1elemf0f2iter := range f22f1f1iter.InstanceRequirements.AcceleratorNames {
								var f22f1f1elemf0f2elem string
								f22f1f1elemf0f2elem = string(*f22f1f1elemf0f2iter)
								f22f1f1elemf0f2 = append(f22f1f1elemf0f2, svcsdktypes.AcceleratorName(f22f1f1elemf0f2elem))
							}
							f22f1f1elemf0.AcceleratorNames = f22f1f1elemf0f2
						}
						if f22f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
							f22f1f1elemf0f3 := &svcsdktypes.AcceleratorTotalMemoryMiBRequest{}
							if f22f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
								maxCopy0 := *f22f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f22f1f1elemf0f3.Max = &maxCopy
							}
							if f22f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
								minCopy0 := *f22f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f22f1f1elemf0f3.Min = &minCopy
							}
							f22f1f1elemf0.AcceleratorTotalMemoryMiB = f22f1f1elemf0f3
						}
						if f22f1f1iter.InstanceRequirements.AcceleratorTypes != nil {
							f22f1f1elemf0f4 := []svcsdktypes.AcceleratorType{}
							for _, f22f1f1elemf0f4iter := range f22f1f1iter.InstanceRequirements.AcceleratorTypes {
								var f22f1f1elemf0f4elem string
								f22f1f1elemf0f4elem = string(*f22f1f1elemf0f4iter)
								f22f1f1elemf0f4 = append(f22f1f1elemf0f4, svcsdktypes.AcceleratorType(f22f1f1elemf0f4elem))
							}
							f22f1f1elemf0.AcceleratorTypes = f22f1f1elemf0f4
						}
						if f22f1f1iter.InstanceRequirements.AllowedInstanceTypes != nil {
							f22f1f1elemf0.AllowedInstanceTypes = aws.ToStringSlice(f22f1f1iter.InstanceRequirements.AllowedInstanceTypes)
						}
						if f22f1f1iter.InstanceRequirements.BareMetal != nil {
							f22f1f1elemf0.BareMetal = svcsdktypes.BareMetal(*f22f1f1iter.InstanceRequirements.BareMetal)
						}
						if f22f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps != nil {
							f22f1f1elemf0f7 := &svcsdktypes.BaselineEbsBandwidthMbpsRequest{}
							if f22f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil {
								maxCopy0 := *f22f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f22f1f1elemf0f7.Max = &maxCopy
							}
							if f22f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil {
								minCopy0 := *f22f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f22f1f1elemf0f7.Min = &minCopy
							}
							f22f1f1elemf0.BaselineEbsBandwidthMbps = f22f1f1elemf0f7
						}
						if f22f1f1iter.InstanceRequirements.BaselinePerformanceFactors != nil {
							f22f1f1elemf0f8 := &svcsdktypes.BaselinePerformanceFactorsRequest{}
							if f22f1f1iter.InstanceRequirements.BaselinePerformanceFactors.CPU != nil {
								f22f1f1elemf0f8f0 := &svcsdktypes.CpuPerformanceFactorRequest{}
								if f22f1f1iter.InstanceRequirements.BaselinePerformanceFactors.CPU.References != nil {
									f22f1f1elemf0f8f0f0 := []svcsdktypes.PerformanceFactorReferenceRequest{}
									for _, f22f1f1elemf0f8f0f0iter := range f22f1f1iter.InstanceRequirements.BaselinePerformanceFactors.CPU.References {
										f22f1f1elemf0f8f0f0elem := &svcsdktypes.PerformanceFactorReferenceRequest{}
										if f22f1f1elemf0f8f0f0iter.InstanceFamily != nil {
											f22f1f1elemf0f8f0f0elem.InstanceFamily = f22f1f1elemf0f8f0f0iter.InstanceFamily
										}
										f22f1f1elemf0f8f0f0 = append(f22f1f1elemf0f8f0f0, *f22f1f1elemf0f8f0f0elem)
									}
									f22f1f1elemf0f8f0.References = f22f1f1elemf0f8f0f0
								}
								f22f1f1elemf0f8.Cpu = f22f1f1elemf0f8f0
							}
							f22f1f1elemf0.BaselinePerformanceFactors = f22f1f1elemf0f8
						}
						if f22f1f1iter.InstanceRequirements.BurstablePerformance != nil {
							f22f1f1elemf0.BurstablePerformance = svcsdktypes.BurstablePerformance(*f22f1f1iter.InstanceRequirements.BurstablePerformance)
						}
						if f22f1f1iter.InstanceRequirements.CPUManufacturers != nil {
							f22f1f1elemf0f10 := []svcsdktypes.CpuManufacturer{}
							for _, f22f1f1elemf0f10iter := range f22f1f1iter.InstanceRequirements.CPUManufacturers {
								var f22f1f1elemf0f10elem string
								f22f1f1elemf0f10elem = string(*f22f1f1elemf0f10iter)
								f22f1f1elemf0f10 = append(f22f1f1elemf0f10, svcsdktypes.CpuManufacturer(f22f1f1elemf0f10elem))
							}
							f22f1f1elemf0.CpuManufacturers = f22f1f1elemf0f10
						}
						if f22f1f1iter.InstanceRequirements.ExcludedInstanceTypes != nil {
							f22f1f1elemf0.ExcludedInstanceTypes = aws.ToStringSlice(f22f1f1iter.InstanceRequirements.ExcludedInstanceTypes)
						}
						if f22f1f1iter.InstanceRequirements.InstanceGenerations != nil {
							f22f1f1elemf0f12 := []svcsdktypes.InstanceGeneration{}
							for _, f22f1f1elemf0f12iter := range f22f1f1iter.InstanceRequirements.InstanceGenerations {
								var f22f1f1elemf0f12elem string
								f22f1f1elemf0f12elem = string(*f22f1f1elemf0f12iter)
								f22f1f1elemf0f12 = append(f22f1f1elemf0f12, svcsdktypes.InstanceGeneration(f22f1f1elemf0f12elem))
							}
							f22f1f1elemf0.InstanceGenerations = f22f1f1elemf0f12
						}
						if f22f1f1iter.InstanceRequirements.LocalStorage != nil {
							f22f1f1elemf0.LocalStorage = svcsdktypes.LocalStorage(*f22f1f1iter.InstanceRequirements.LocalStorage)
						}
						if f22f1f1iter.InstanceRequirements.LocalStorageTypes != nil {
							f22f1f1elemf0f14 := []svcsdktypes.LocalStorageType{}
							for _, f22f1f1elemf0f14iter := range f22f1f1iter.InstanceRequirements.LocalStorageTypes {
								var f22f1f1elemf0f14elem string
								f22f1f1elemf0f14elem = string(*f22f1f1elemf0f14iter)
								f22f1f1elemf0f14 = append(f22f1f1elemf0f14, svcsdktypes.LocalStorageType(f22f1f1elemf0f14elem))
							}
							f22f1f1elemf0.LocalStorageTypes = f22f1f1elemf0f14
						}
						if f22f1f1iter.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice != nil {
							maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0 := *f22f1f1iter.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice
							if maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0 > math.MaxInt32 || maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field MaxSpotPriceAsPercentageOfOptimalOnDemandPrice is of type int32")
							}
							maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy := int32(maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0)
							f22f1f1elemf0.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice = &maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy
						}
						if f22f1f1iter.InstanceRequirements.MemoryGiBPerVCPU != nil {
							f22f1f1elemf0f16 := &svcsdktypes.MemoryGiBPerVCpuRequest{}
							if f22f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max != nil {
								f22f1f1elemf0f16.Max = f22f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max
							}
							if f22f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min != nil {
								f22f1f1elemf0f16.Min = f22f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min
							}
							f22f1f1elemf0.MemoryGiBPerVCpu = f22f1f1elemf0f16
						}
						if f22f1f1iter.InstanceRequirements.MemoryMiB != nil {
							f22f1f1elemf0f17 := &svcsdktypes.MemoryMiBRequest{}
							if f22f1f1iter.InstanceRequirements.MemoryMiB.Max != nil {
								maxCopy0 := *f22f1f1iter.InstanceRequirements.MemoryMiB.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f22f1f1elemf0f17.Max = &maxCopy
							}
							if f22f1f1iter.InstanceRequirements.MemoryMiB.Min != nil {
								minCopy0 := *f22f1f1iter.InstanceRequirements.MemoryMiB.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f22f1f1elemf0f17.Min = &minCopy
							}
							f22f1f1elemf0.MemoryMiB = f22f1f1elemf0f17
						}
						if f22f1f1iter.InstanceRequirements.NetworkBandwidthGbps != nil {
							f22f1f1elemf0f18 := &svcsdktypes.NetworkBandwidthGbpsRequest{}
							if f22f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Max != nil {
								f22f1f1elemf0f18.Max = f22f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Max
							}
							if f22f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Min != nil {
								f22f1f1elemf0f18.Min = f22f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Min
							}
							f22f1f1elemf0.NetworkBandwidthGbps = f22f1f1elemf0f18
						}
						if f22f1f1iter.InstanceRequirements.NetworkInterfaceCount != nil {
							f22f1f1elemf0f19 := &svcsdktypes.NetworkInterfaceCountRequest{}
							if f22f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max != nil {
								maxCopy0 := *f22f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f22f1f1elemf0f19.Max = &maxCopy
							}
							if f22f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min != nil {
								minCopy0 := *f22f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f22f1f1elemf0f19.Min = &minCopy
							}
							f22f1f1elemf0.NetworkInterfaceCount = f22f1f1elemf0f19
						}
						if f22f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
							onDemandMaxPricePercentageOverLowestPriceCopy0 := *f22f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice
							if onDemandMaxPricePercentageOverLowestPriceCopy0 > math.MaxInt32 || onDemandMaxPricePercentageOverLowestPriceCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field OnDemandMaxPricePercentageOverLowestPrice is of type int32")
							}
							onDemandMaxPricePercentageOverLowestPriceCopy := int32(onDemandMaxPricePercentageOverLowestPriceCopy0)
							f22f1f1elemf0.OnDemandMaxPricePercentageOverLowestPrice = &onDemandMaxPricePercentageOverLowestPriceCopy
						}
						if f22f1f1iter.InstanceRequirements.RequireHibernateSupport != nil {
							f22f1f1elemf0.RequireHibernateSupport = f22f1f1iter.InstanceRequirements.RequireHibernateSupport
						}
						if f22f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
							spotMaxPricePercentageOverLowestPriceCopy0 := *f22f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice
							if spotMaxPricePercentageOverLowestPriceCopy0 > math.MaxInt32 || spotMaxPricePercentageOverLowestPriceCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field SpotMaxPricePercentageOverLowestPrice is of type int32")
							}
							spotMaxPricePercentageOverLowestPriceCopy := int32(spotMaxPricePercentageOverLowestPriceCopy0)
							f22f1f1elemf0.SpotMaxPricePercentageOverLowestPrice = &spotMaxPricePercentageOverLowestPriceCopy
						}
						if f22f1f1iter.InstanceRequirements.TotalLocalStorageGB != nil {
							f22f1f1elemf0f23 := &svcsdktypes.TotalLocalStorageGBRequest{}
							if f22f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max != nil {
								f22f1f1elemf0f23.Max = f22f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max
							}
							if f22f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min != nil {
								f22f1f1elemf0f23.Min = f22f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min
							}
							f22f1f1elemf0.TotalLocalStorageGB = f22f1f1elemf0f23
						}
						if f22f1f1iter.InstanceRequirements.VCPUCount != nil {
							f22f1f1elemf0f24 := &svcsdktypes.VCpuCountRequest{}
							if f22f1f1iter.InstanceRequirements.VCPUCount.Max != nil {
								maxCopy0 := *f22f1f1iter.InstanceRequirements.VCPUCount.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f22f1f1elemf0f24.Max = &maxCopy
							}
							if f22f1f1iter.InstanceRequirements.VCPUCount.Min != nil {
								minCopy0 := *f22f1f1iter.InstanceRequirements.VCPUCount.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f22f1f1elemf0f24.Min = &minCopy
							}
							f22f1f1elemf0.VCpuCount = f22f1f1elemf0f24
						}
						f22f1f1elem.InstanceRequirements = f22f1f1elemf0
					}
					if f22f1f1iter.InstanceType != nil {
						f22f1f1elem.InstanceType = f22f1f1iter.InstanceType
					}
					if f22f1f1iter.LaunchTemplateSpecification != nil {
						f22f1f1elemf2 := &svcsdktypes.LaunchTemplateSpecification{}
						if f22f1f1iter.LaunchTemplateSpecification.LaunchTemplateID != nil {
							f22f1f1elemf2.LaunchTemplateId = f22f1f1iter.LaunchTemplateSpecification.LaunchTemplateID
						}
						if f22f1f1iter.LaunchTemplateSpecification.LaunchTemplateName != nil {
							f22f1f1elemf2.LaunchTemplateName = f22f1f1iter.LaunchTemplateSpecification.LaunchTemplateName
						}
						if f22f1f1iter.LaunchTemplateSpecification.Version != nil {
							f22f1f1elemf2.Version = f22f1f1iter.LaunchTemplateSpecification.Version
						}
						f22f1f1elem.LaunchTemplateSpecification = f22f1f1elemf2
					}
					if f22f1f1iter.WeightedCapacity != nil {
						f22f1f1elem.WeightedCapacity = f22f1f1iter.WeightedCapacity
					}
					f22f1f1 = append(f22f1f1, *f22f1f1elem)
				}
				f22f1.Overrides = f22f1f1
			}
			f22.LaunchTemplate = f22f1
		}
		res.MixedInstancesPolicy = f22
	}
	if r.ko.Spec.NewInstancesProtectedFromScaleIn != nil {
		res.NewInstancesProtectedFromScaleIn = r.ko.Spec.NewInstancesProtectedFromScaleIn
	}
	if r.ko.Spec.PlacementGroup != nil {
		res.PlacementGroup = r.ko.Spec.PlacementGroup
	}
	if r.ko.Spec.ServiceLinkedRoleARN != nil {
		res.ServiceLinkedRoleARN = r.ko.Spec.ServiceLinkedRoleARN
	}
	if r.ko.Spec.SkipZonalShiftValidation != nil {
		res.SkipZonalShiftValidation = r.ko.Spec.SkipZonalShiftValidation
	}
	if r.ko.Spec.Tags != nil {
		f27 := []svcsdktypes.Tag{}
		for _, f27iter := range r.ko.Spec.Tags {
			f27elem := &svcsdktypes.Tag{}
			if f27iter.Key != nil {
				f27elem.Key = f27iter.Key
			}
			if f27iter.PropagateAtLaunch != nil {
				f27elem.PropagateAtLaunch = f27iter.PropagateAtLaunch
			}
			if f27iter.ResourceID != nil {
				f27elem.ResourceId = f27iter.ResourceID
			}
			if f27iter.ResourceType != nil {
				f27elem.ResourceType = f27iter.ResourceType
			}
			if f27iter.Value != nil {
				f27elem.Value = f27iter.Value
			}
			f27 = append(f27, *f27elem)
		}
		res.Tags = f27
	}
	if r.ko.Spec.TargetGroupARNs != nil {
		res.TargetGroupARNs = aws.ToStringSlice(r.ko.Spec.TargetGroupARNs)
	}
	if r.ko.Spec.TerminationPolicies != nil {
		res.TerminationPolicies = aws.ToStringSlice(r.ko.Spec.TerminationPolicies)
	}
	if r.ko.Spec.TrafficSources != nil {
		f30 := []svcsdktypes.TrafficSourceIdentifier{}
		for _, f30iter := range r.ko.Spec.TrafficSources {
			f30elem := &svcsdktypes.TrafficSourceIdentifier{}
			if f30iter.Identifier != nil {
				f30elem.Identifier = f30iter.Identifier
			}
			if f30iter.Type != nil {
				f30elem.Type = f30iter.Type
			}
			f30 = append(f30, *f30elem)
		}
		res.TrafficSources = f30
	}
	if r.ko.Spec.VPCZoneIdentifier != nil {
		res.VPCZoneIdentifier = r.ko.Spec.VPCZoneIdentifier
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		err := rm.syncTags(
			ctx,
			latest,
			desired,
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateAutoScalingGroupOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateAutoScalingGroup(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateAutoScalingGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateAutoScalingGroupInput, error) {
	res := &svcsdk.UpdateAutoScalingGroupInput{}

	if r.ko.Spec.AutoScalingGroupName != nil {
		res.AutoScalingGroupName = r.ko.Spec.AutoScalingGroupName
	}
	if r.ko.Spec.AvailabilityZoneDistribution != nil {
		f1 := &svcsdktypes.AvailabilityZoneDistribution{}
		if r.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy != nil {
			f1.CapacityDistributionStrategy = svcsdktypes.CapacityDistributionStrategy(*r.ko.Spec.AvailabilityZoneDistribution.CapacityDistributionStrategy)
		}
		res.AvailabilityZoneDistribution = f1
	}
	if r.ko.Spec.AvailabilityZoneImpairmentPolicy != nil {
		f2 := &svcsdktypes.AvailabilityZoneImpairmentPolicy{}
		if r.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior != nil {
			f2.ImpairedZoneHealthCheckBehavior = svcsdktypes.ImpairedZoneHealthCheckBehavior(*r.ko.Spec.AvailabilityZoneImpairmentPolicy.ImpairedZoneHealthCheckBehavior)
		}
		if r.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled != nil {
			f2.ZonalShiftEnabled = r.ko.Spec.AvailabilityZoneImpairmentPolicy.ZonalShiftEnabled
		}
		res.AvailabilityZoneImpairmentPolicy = f2
	}
	if r.ko.Spec.AvailabilityZones != nil {
		res.AvailabilityZones = aws.ToStringSlice(r.ko.Spec.AvailabilityZones)
	}
	if r.ko.Spec.CapacityRebalance != nil {
		res.CapacityRebalance = r.ko.Spec.CapacityRebalance
	}
	if r.ko.Spec.CapacityReservationSpecification != nil {
		f5 := &svcsdktypes.CapacityReservationSpecification{}
		if r.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference != nil {
			f5.CapacityReservationPreference = svcsdktypes.CapacityReservationPreference(*r.ko.Spec.CapacityReservationSpecification.CapacityReservationPreference)
		}
		if r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget != nil {
			f5f1 := &svcsdktypes.CapacityReservationTarget{}
			if r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs != nil {
				f5f1.CapacityReservationIds = aws.ToStringSlice(r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationIDs)
			}
			if r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs != nil {
				f5f1.CapacityReservationResourceGroupArns = aws.ToStringSlice(r.ko.Spec.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupARNs)
			}
			f5.CapacityReservationTarget = f5f1
		}
		res.CapacityReservationSpecification = f5
	}
	if r.ko.Spec.Context != nil {
		res.Context = r.ko.Spec.Context
	}
	if r.ko.Spec.DefaultCooldown != nil {
		defaultCooldownCopy0 := *r.ko.Spec.DefaultCooldown
		if defaultCooldownCopy0 > math.MaxInt32 || defaultCooldownCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DefaultCooldown is of type int32")
		}
		defaultCooldownCopy := int32(defaultCooldownCopy0)
		res.DefaultCooldown = &defaultCooldownCopy
	}
	if r.ko.Spec.DefaultInstanceWarmup != nil {
		defaultInstanceWarmupCopy0 := *r.ko.Spec.DefaultInstanceWarmup
		if defaultInstanceWarmupCopy0 > math.MaxInt32 || defaultInstanceWarmupCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DefaultInstanceWarmup is of type int32")
		}
		defaultInstanceWarmupCopy := int32(defaultInstanceWarmupCopy0)
		res.DefaultInstanceWarmup = &defaultInstanceWarmupCopy
	}
	if r.ko.Spec.DesiredCapacity != nil {
		desiredCapacityCopy0 := *r.ko.Spec.DesiredCapacity
		if desiredCapacityCopy0 > math.MaxInt32 || desiredCapacityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field DesiredCapacity is of type int32")
		}
		desiredCapacityCopy := int32(desiredCapacityCopy0)
		res.DesiredCapacity = &desiredCapacityCopy
	}
	if r.ko.Spec.DesiredCapacityType != nil {
		res.DesiredCapacityType = r.ko.Spec.DesiredCapacityType
	}
	if r.ko.Spec.HealthCheckGracePeriod != nil {
		healthCheckGracePeriodCopy0 := *r.ko.Spec.HealthCheckGracePeriod
		if healthCheckGracePeriodCopy0 > math.MaxInt32 || healthCheckGracePeriodCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field HealthCheckGracePeriod is of type int32")
		}
		healthCheckGracePeriodCopy := int32(healthCheckGracePeriodCopy0)
		res.HealthCheckGracePeriod = &healthCheckGracePeriodCopy
	}
	if r.ko.Spec.HealthCheckType != nil {
		res.HealthCheckType = r.ko.Spec.HealthCheckType
	}
	if r.ko.Spec.InstanceMaintenancePolicy != nil {
		f13 := &svcsdktypes.InstanceMaintenancePolicy{}
		if r.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage != nil {
			maxHealthyPercentageCopy0 := *r.ko.Spec.InstanceMaintenancePolicy.MaxHealthyPercentage
			if maxHealthyPercentageCopy0 > math.MaxInt32 || maxHealthyPercentageCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field MaxHealthyPercentage is of type int32")
			}
			maxHealthyPercentageCopy := int32(maxHealthyPercentageCopy0)
			f13.MaxHealthyPercentage = &maxHealthyPercentageCopy
		}
		if r.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage != nil {
			minHealthyPercentageCopy0 := *r.ko.Spec.InstanceMaintenancePolicy.MinHealthyPercentage
			if minHealthyPercentageCopy0 > math.MaxInt32 || minHealthyPercentageCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field MinHealthyPercentage is of type int32")
			}
			minHealthyPercentageCopy := int32(minHealthyPercentageCopy0)
			f13.MinHealthyPercentage = &minHealthyPercentageCopy
		}
		res.InstanceMaintenancePolicy = f13
	}
	if r.ko.Spec.LaunchConfigurationName != nil {
		res.LaunchConfigurationName = r.ko.Spec.LaunchConfigurationName
	}
	if r.ko.Spec.LaunchTemplate != nil {
		f15 := &svcsdktypes.LaunchTemplateSpecification{}
		if r.ko.Spec.LaunchTemplate.LaunchTemplateID != nil {
			f15.LaunchTemplateId = r.ko.Spec.LaunchTemplate.LaunchTemplateID
		}
		if r.ko.Spec.LaunchTemplate.LaunchTemplateName != nil {
			f15.LaunchTemplateName = r.ko.Spec.LaunchTemplate.LaunchTemplateName
		}
		if r.ko.Spec.LaunchTemplate.Version != nil {
			f15.Version = r.ko.Spec.LaunchTemplate.Version
		}
		res.LaunchTemplate = f15
	}
	if r.ko.Spec.MaxInstanceLifetime != nil {
		maxInstanceLifetimeCopy0 := *r.ko.Spec.MaxInstanceLifetime
		if maxInstanceLifetimeCopy0 > math.MaxInt32 || maxInstanceLifetimeCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxInstanceLifetime is of type int32")
		}
		maxInstanceLifetimeCopy := int32(maxInstanceLifetimeCopy0)
		res.MaxInstanceLifetime = &maxInstanceLifetimeCopy
	}
	if r.ko.Spec.MaxSize != nil {
		maxSizeCopy0 := *r.ko.Spec.MaxSize
		if maxSizeCopy0 > math.MaxInt32 || maxSizeCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MaxSize is of type int32")
		}
		maxSizeCopy := int32(maxSizeCopy0)
		res.MaxSize = &maxSizeCopy
	}
	if r.ko.Spec.MinSize != nil {
		minSizeCopy0 := *r.ko.Spec.MinSize
		if minSizeCopy0 > math.MaxInt32 || minSizeCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field MinSize is of type int32")
		}
		minSizeCopy := int32(minSizeCopy0)
		res.MinSize = &minSizeCopy
	}
	if r.ko.Spec.MixedInstancesPolicy != nil {
		f19 := &svcsdktypes.MixedInstancesPolicy{}
		if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution != nil {
			f19f0 := &svcsdktypes.InstancesDistribution{}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy != nil {
				f19f0.OnDemandAllocationStrategy = r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandAllocationStrategy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity != nil {
				onDemandBaseCapacityCopy0 := *r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandBaseCapacity
				if onDemandBaseCapacityCopy0 > math.MaxInt32 || onDemandBaseCapacityCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field OnDemandBaseCapacity is of type int32")
				}
				onDemandBaseCapacityCopy := int32(onDemandBaseCapacityCopy0)
				f19f0.OnDemandBaseCapacity = &onDemandBaseCapacityCopy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity != nil {
				onDemandPercentageAboveBaseCapacityCopy0 := *r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.OnDemandPercentageAboveBaseCapacity
				if onDemandPercentageAboveBaseCapacityCopy0 > math.MaxInt32 || onDemandPercentageAboveBaseCapacityCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field OnDemandPercentageAboveBaseCapacity is of type int32")
				}
				onDemandPercentageAboveBaseCapacityCopy := int32(onDemandPercentageAboveBaseCapacityCopy0)
				f19f0.OnDemandPercentageAboveBaseCapacity = &onDemandPercentageAboveBaseCapacityCopy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy != nil {
				f19f0.SpotAllocationStrategy = r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotAllocationStrategy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools != nil {
				spotInstancePoolsCopy0 := *r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotInstancePools
				if spotInstancePoolsCopy0 > math.MaxInt32 || spotInstancePoolsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field SpotInstancePools is of type int32")
				}
				spotInstancePoolsCopy := int32(spotInstancePoolsCopy0)
				f19f0.SpotInstancePools = &spotInstancePoolsCopy
			}
			if r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice != nil {
				f19f0.SpotMaxPrice = r.ko.Spec.MixedInstancesPolicy.InstancesDistribution.SpotMaxPrice
			}
			f19.InstancesDistribution = f19f0
		}
		if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate != nil {
			f19f1 := &svcsdktypes.LaunchTemplate{}
			if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification != nil {
				f19f1f0 := &svcsdktypes.LaunchTemplateSpecification{}
				if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID != nil {
					f19f1f0.LaunchTemplateId = r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateID
				}
				if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName != nil {
					f19f1f0.LaunchTemplateName = r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName
				}
				if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version != nil {
					f19f1f0.Version = r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.Version
				}
				f19f1.LaunchTemplateSpecification = f19f1f0
			}
			if r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides != nil {
				f19f1f1 := []svcsdktypes.LaunchTemplateOverrides{}
				for _, f19f1f1iter := range r.ko.Spec.MixedInstancesPolicy.LaunchTemplate.Overrides {
					f19f1f1elem := &svcsdktypes.LaunchTemplateOverrides{}
					if f19f1f1iter.InstanceRequirements != nil {
						f19f1f1elemf0 := &svcsdktypes.InstanceRequirements{}
						if f19f1f1iter.InstanceRequirements.AcceleratorCount != nil {
							f19f1f1elemf0f0 := &svcsdktypes.AcceleratorCountRequest{}
							if f19f1f1iter.InstanceRequirements.AcceleratorCount.Max != nil {
								maxCopy0 := *f19f1f1iter.InstanceRequirements.AcceleratorCount.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f19f1f1elemf0f0.Max = &maxCopy
							}
							if f19f1f1iter.InstanceRequirements.AcceleratorCount.Min != nil {
								minCopy0 := *f19f1f1iter.InstanceRequirements.AcceleratorCount.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f19f1f1elemf0f0.Min = &minCopy
							}
							f19f1f1elemf0.AcceleratorCount = f19f1f1elemf0f0
						}
						if f19f1f1iter.InstanceRequirements.AcceleratorManufacturers != nil {
							f19f1f1elemf0f1 := []svcsdktypes.AcceleratorManufacturer{}
							for _, f19f1f1elemf0f1iter := range f19f1f1iter.InstanceRequirements.AcceleratorManufacturers {
								var f19f1f1elemf0f1elem string
								f19f1f1elemf0f1elem = string(*f19f1f1elemf0f1iter)
								f19f1f1elemf0f1 = append(f19f1f1elemf0f1, svcsdktypes.AcceleratorManufacturer(f19f1f1elemf0f1elem))
							}
							f19f1f1elemf0.AcceleratorManufacturers = f19f1f1elemf0f1
						}
						if f19f1f1iter.InstanceRequirements.AcceleratorNames != nil {
							f19f1f1elemf0f2 := []svcsdktypes.AcceleratorName{}
							for _, f19f1f1elemf0f2iter := range f19f1f1iter.InstanceRequirements.AcceleratorNames {
								var f19f1f1elemf0f2elem string
								f19f1f1elemf0f2elem = string(*f19f1f1elemf0f2iter)
								f19f1f1elemf0f2 = append(f19f1f1elemf0f2, svcsdktypes.AcceleratorName(f19f1f1elemf0f2elem))
							}
							f19f1f1elemf0.AcceleratorNames = f19f1f1elemf0f2
						}
						if f19f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
							f19f1f1elemf0f3 := &svcsdktypes.AcceleratorTotalMemoryMiBRequest{}
							if f19f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
								maxCopy0 := *f19f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f19f1f1elemf0f3.Max = &maxCopy
							}
							if f19f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
								minCopy0 := *f19f1f1iter.InstanceRequirements.AcceleratorTotalMemoryMiB.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f19f1f1elemf0f3.Min = &minCopy
							}
							f19f1f1elemf0.AcceleratorTotalMemoryMiB = f19f1f1elemf0f3
						}
						if f19f1f1iter.InstanceRequirements.AcceleratorTypes != nil {
							f19f1f1elemf0f4 := []svcsdktypes.AcceleratorType{}
							for _, f19f1f1elemf0f4iter := range f19f1f1iter.InstanceRequirements.AcceleratorTypes {
								var f19f1f1elemf0f4elem string
								f19f1f1elemf0f4elem = string(*f19f1f1elemf0f4iter)
								f19f1f1elemf0f4 = append(f19f1f1elemf0f4, svcsdktypes.AcceleratorType(f19f1f1elemf0f4elem))
							}
							f19f1f1elemf0.AcceleratorTypes = f19f1f1elemf0f4
						}
						if f19f1f1iter.InstanceRequirements.AllowedInstanceTypes != nil {
							f19f1f1elemf0.AllowedInstanceTypes = aws.ToStringSlice(f19f1f1iter.InstanceRequirements.AllowedInstanceTypes)
						}
						if f19f1f1iter.InstanceRequirements.BareMetal != nil {
							f19f1f1elemf0.BareMetal = svcsdktypes.BareMetal(*f19f1f1iter.InstanceRequirements.BareMetal)
						}
						if f19f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps != nil {
							f19f1f1elemf0f7 := &svcsdktypes.BaselineEbsBandwidthMbpsRequest{}
							if f19f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil {
								maxCopy0 := *f19f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f19f1f1elemf0f7.Max = &maxCopy
							}
							if f19f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil {
								minCopy0 := *f19f1f1iter.InstanceRequirements.BaselineEBSBandwidthMbps.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f19f1f1elemf0f7.Min = &minCopy
							}
							f19f1f1elemf0.BaselineEbsBandwidthMbps = f19f1f1elemf0f7
						}
						if f19f1f1iter.InstanceRequirements.BaselinePerformanceFactors != nil {
							f19f1f1elemf0f8 := &svcsdktypes.BaselinePerformanceFactorsRequest{}
							if f19f1f1iter.InstanceRequirements.BaselinePerformanceFactors.CPU != nil {
								f19f1f1elemf0f8f0 := &svcsdktypes.CpuPerformanceFactorRequest{}
								if f19f1f1iter.InstanceRequirements.BaselinePerformanceFactors.CPU.References != nil {
									f19f1f1elemf0f8f0f0 := []svcsdktypes.PerformanceFactorReferenceRequest{}
									for _, f19f1f1elemf0f8f0f0iter := range f19f1f1iter.InstanceRequirements.BaselinePerformanceFactors.CPU.References {
										f19f1f1elemf0f8f0f0elem := &svcsdktypes.PerformanceFactorReferenceRequest{}
										if f19f1f1elemf0f8f0f0iter.InstanceFamily != nil {
											f19f1f1elemf0f8f0f0elem.InstanceFamily = f19f1f1elemf0f8f0f0iter.InstanceFamily
										}
										f19f1f1elemf0f8f0f0 = append(f19f1f1elemf0f8f0f0, *f19f1f1elemf0f8f0f0elem)
									}
									f19f1f1elemf0f8f0.References = f19f1f1elemf0f8f0f0
								}
								f19f1f1elemf0f8.Cpu = f19f1f1elemf0f8f0
							}
							f19f1f1elemf0.BaselinePerformanceFactors = f19f1f1elemf0f8
						}
						if f19f1f1iter.InstanceRequirements.BurstablePerformance != nil {
							f19f1f1elemf0.BurstablePerformance = svcsdktypes.BurstablePerformance(*f19f1f1iter.InstanceRequirements.BurstablePerformance)
						}
						if f19f1f1iter.InstanceRequirements.CPUManufacturers != nil {
							f19f1f1elemf0f10 := []svcsdktypes.CpuManufacturer{}
							for _, f19f1f1elemf0f10iter := range f19f1f1iter.InstanceRequirements.CPUManufacturers {
								var f19f1f1elemf0f10elem string
								f19f1f1elemf0f10elem = string(*f19f1f1elemf0f10iter)
								f19f1f1elemf0f10 = append(f19f1f1elemf0f10, svcsdktypes.CpuManufacturer(f19f1f1elemf0f10elem))
							}
							f19f1f1elemf0.CpuManufacturers = f19f1f1elemf0f10
						}
						if f19f1f1iter.InstanceRequirements.ExcludedInstanceTypes != nil {
							f19f1f1elemf0.ExcludedInstanceTypes = aws.ToStringSlice(f19f1f1iter.InstanceRequirements.ExcludedInstanceTypes)
						}
						if f19f1f1iter.InstanceRequirements.InstanceGenerations != nil {
							f19f1f1elemf0f12 := []svcsdktypes.InstanceGeneration{}
							for _, f19f1f1elemf0f12iter := range f19f1f1iter.InstanceRequirements.InstanceGenerations {
								var f19f1f1elemf0f12elem string
								f19f1f1elemf0f12elem = string(*f19f1f1elemf0f12iter)
								f19f1f1elemf0f12 = append(f19f1f1elemf0f12, svcsdktypes.InstanceGeneration(f19f1f1elemf0f12elem))
							}
							f19f1f1elemf0.InstanceGenerations = f19f1f1elemf0f12
						}
						if f19f1f1iter.InstanceRequirements.LocalStorage != nil {
							f19f1f1elemf0.LocalStorage = svcsdktypes.LocalStorage(*f19f1f1iter.InstanceRequirements.LocalStorage)
						}
						if f19f1f1iter.InstanceRequirements.LocalStorageTypes != nil {
							f19f1f1elemf0f14 := []svcsdktypes.LocalStorageType{}
							for _, f19f1f1elemf0f14iter := range f19f1f1iter.InstanceRequirements.LocalStorageTypes {
								var f19f1f1elemf0f14elem string
								f19f1f1elemf0f14elem = string(*f19f1f1elemf0f14iter)
								f19f1f1elemf0f14 = append(f19f1f1elemf0f14, svcsdktypes.LocalStorageType(f19f1f1elemf0f14elem))
							}
							f19f1f1elemf0.LocalStorageTypes = f19f1f1elemf0f14
						}
						if f19f1f1iter.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice != nil {
							maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0 := *f19f1f1iter.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice
							if maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0 > math.MaxInt32 || maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field MaxSpotPriceAsPercentageOfOptimalOnDemandPrice is of type int32")
							}
							maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy := int32(maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy0)
							f19f1f1elemf0.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice = &maxSpotPriceAsPercentageOfOptimalOnDemandPriceCopy
						}
						if f19f1f1iter.InstanceRequirements.MemoryGiBPerVCPU != nil {
							f19f1f1elemf0f16 := &svcsdktypes.MemoryGiBPerVCpuRequest{}
							if f19f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max != nil {
								f19f1f1elemf0f16.Max = f19f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Max
							}
							if f19f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min != nil {
								f19f1f1elemf0f16.Min = f19f1f1iter.InstanceRequirements.MemoryGiBPerVCPU.Min
							}
							f19f1f1elemf0.MemoryGiBPerVCpu = f19f1f1elemf0f16
						}
						if f19f1f1iter.InstanceRequirements.MemoryMiB != nil {
							f19f1f1elemf0f17 := &svcsdktypes.MemoryMiBRequest{}
							if f19f1f1iter.InstanceRequirements.MemoryMiB.Max != nil {
								maxCopy0 := *f19f1f1iter.InstanceRequirements.MemoryMiB.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f19f1f1elemf0f17.Max = &maxCopy
							}
							if f19f1f1iter.InstanceRequirements.MemoryMiB.Min != nil {
								minCopy0 := *f19f1f1iter.InstanceRequirements.MemoryMiB.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f19f1f1elemf0f17.Min = &minCopy
							}
							f19f1f1elemf0.MemoryMiB = f19f1f1elemf0f17
						}
						if f19f1f1iter.InstanceRequirements.NetworkBandwidthGbps != nil {
							f19f1f1elemf0f18 := &svcsdktypes.NetworkBandwidthGbpsRequest{}
							if f19f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Max != nil {
								f19f1f1elemf0f18.Max = f19f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Max
							}
							if f19f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Min != nil {
								f19f1f1elemf0f18.Min = f19f1f1iter.InstanceRequirements.NetworkBandwidthGbps.Min
							}
							f19f1f1elemf0.NetworkBandwidthGbps = f19f1f1elemf0f18
						}
						if f19f1f1iter.InstanceRequirements.NetworkInterfaceCount != nil {
							f19f1f1elemf0f19 := &svcsdktypes.NetworkInterfaceCountRequest{}
							if f19f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max != nil {
								maxCopy0 := *f19f1f1iter.InstanceRequirements.NetworkInterfaceCount.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f19f1f1elemf0f19.Max = &maxCopy
							}
							if f19f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min != nil {
								minCopy0 := *f19f1f1iter.InstanceRequirements.NetworkInterfaceCount.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f19f1f1elemf0f19.Min = &minCopy
							}
							f19f1f1elemf0.NetworkInterfaceCount = f19f1f1elemf0f19
						}
						if f19f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
							onDemandMaxPricePercentageOverLowestPriceCopy0 := *f19f1f1iter.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice
							if onDemandMaxPricePercentageOverLowestPriceCopy0 > math.MaxInt32 || onDemandMaxPricePercentageOverLowestPriceCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field OnDemandMaxPricePercentageOverLowestPrice is of type int32")
							}
							onDemandMaxPricePercentageOverLowestPriceCopy := int32(onDemandMaxPricePercentageOverLowestPriceCopy0)
							f19f1f1elemf0.OnDemandMaxPricePercentageOverLowestPrice = &onDemandMaxPricePercentageOverLowestPriceCopy
						}
						if f19f1f1iter.InstanceRequirements.RequireHibernateSupport != nil {
							f19f1f1elemf0.RequireHibernateSupport = f19f1f1iter.InstanceRequirements.RequireHibernateSupport
						}
						if f19f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
							spotMaxPricePercentageOverLowestPriceCopy0 := *f19f1f1iter.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice
							if spotMaxPricePercentageOverLowestPriceCopy0 > math.MaxInt32 || spotMaxPricePercentageOverLowestPriceCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field SpotMaxPricePercentageOverLowestPrice is of type int32")
							}
							spotMaxPricePercentageOverLowestPriceCopy := int32(spotMaxPricePercentageOverLowestPriceCopy0)
							f19f1f1elemf0.SpotMaxPricePercentageOverLowestPrice = &spotMaxPricePercentageOverLowestPriceCopy
						}
						if f19f1f1iter.InstanceRequirements.TotalLocalStorageGB != nil {
							f19f1f1elemf0f23 := &svcsdktypes.TotalLocalStorageGBRequest{}
							if f19f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max != nil {
								f19f1f1elemf0f23.Max = f19f1f1iter.InstanceRequirements.TotalLocalStorageGB.Max
							}
							if f19f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min != nil {
								f19f1f1elemf0f23.Min = f19f1f1iter.InstanceRequirements.TotalLocalStorageGB.Min
							}
							f19f1f1elemf0.TotalLocalStorageGB = f19f1f1elemf0f23
						}
						if f19f1f1iter.InstanceRequirements.VCPUCount != nil {
							f19f1f1elemf0f24 := &svcsdktypes.VCpuCountRequest{}
							if f19f1f1iter.InstanceRequirements.VCPUCount.Max != nil {
								maxCopy0 := *f19f1f1iter.InstanceRequirements.VCPUCount.Max
								if maxCopy0 > math.MaxInt32 || maxCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Max is of type int32")
								}
								maxCopy := int32(maxCopy0)
								f19f1f1elemf0f24.Max = &maxCopy
							}
							if f19f1f1iter.InstanceRequirements.VCPUCount.Min != nil {
								minCopy0 := *f19f1f1iter.InstanceRequirements.VCPUCount.Min
								if minCopy0 > math.MaxInt32 || minCopy0 < math.MinInt32 {
									return nil, fmt.Errorf("error: field Min is of type int32")
								}
								minCopy := int32(minCopy0)
								f19f1f1elemf0f24.Min = &minCopy
							}
							f19f1f1elemf0.VCpuCount = f19f1f1elemf0f24
						}
						f19f1f1elem.InstanceRequirements = f19f1f1elemf0
					}
					if f19f1f1iter.InstanceType != nil {
						f19f1f1elem.InstanceType = f19f1f1iter.InstanceType
					}
					if f19f1f1iter.LaunchTemplateSpecification != nil {
						f19f1f1elemf2 := &svcsdktypes.LaunchTemplateSpecification{}
						if f19f1f1iter.LaunchTemplateSpecification.LaunchTemplateID != nil {
							f19f1f1elemf2.LaunchTemplateId = f19f1f1iter.LaunchTemplateSpecification.LaunchTemplateID
						}
						if f19f1f1iter.LaunchTemplateSpecification.LaunchTemplateName != nil {
							f19f1f1elemf2.LaunchTemplateName = f19f1f1iter.LaunchTemplateSpecification.LaunchTemplateName
						}
						if f19f1f1iter.LaunchTemplateSpecification.Version != nil {
							f19f1f1elemf2.Version = f19f1f1iter.LaunchTemplateSpecification.Version
						}
						f19f1f1elem.LaunchTemplateSpecification = f19f1f1elemf2
					}
					if f19f1f1iter.WeightedCapacity != nil {
						f19f1f1elem.WeightedCapacity = f19f1f1iter.WeightedCapacity
					}
					f19f1f1 = append(f19f1f1, *f19f1f1elem)
				}
				f19f1.Overrides = f19f1f1
			}
			f19.LaunchTemplate = f19f1
		}
		res.MixedInstancesPolicy = f19
	}
	if r.ko.Spec.NewInstancesProtectedFromScaleIn != nil {
		res.NewInstancesProtectedFromScaleIn = r.ko.Spec.NewInstancesProtectedFromScaleIn
	}
	if r.ko.Spec.PlacementGroup != nil {
		res.PlacementGroup = r.ko.Spec.PlacementGroup
	}
	if r.ko.Spec.ServiceLinkedRoleARN != nil {
		res.ServiceLinkedRoleARN = r.ko.Spec.ServiceLinkedRoleARN
	}
	if r.ko.Spec.SkipZonalShiftValidation != nil {
		res.SkipZonalShiftValidation = r.ko.Spec.SkipZonalShiftValidation
	}
	if r.ko.Spec.TerminationPolicies != nil {
		res.TerminationPolicies = aws.ToStringSlice(r.ko.Spec.TerminationPolicies)
	}
	if r.ko.Spec.VPCZoneIdentifier != nil {
		res.VPCZoneIdentifier = r.ko.Spec.VPCZoneIdentifier
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAutoScalingGroupOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAutoScalingGroup(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAutoScalingGroup", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAutoScalingGroupInput, error) {
	res := &svcsdk.DeleteAutoScalingGroupInput{}

	if r.ko.Spec.AutoScalingGroupName != nil {
		res.AutoScalingGroupName = r.ko.Spec.AutoScalingGroupName
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AutoScalingGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
