// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AcceleratorManufacturer string

const (
	AcceleratorManufacturer_amazon_web_services AcceleratorManufacturer = "amazon-web-services"
	AcceleratorManufacturer_amd                 AcceleratorManufacturer = "amd"
	AcceleratorManufacturer_nvidia              AcceleratorManufacturer = "nvidia"
	AcceleratorManufacturer_xilinx              AcceleratorManufacturer = "xilinx"
)

type AcceleratorName string

const (
	AcceleratorName_a100            AcceleratorName = "a100"
	AcceleratorName_k80             AcceleratorName = "k80"
	AcceleratorName_m60             AcceleratorName = "m60"
	AcceleratorName_radeon_pro_v520 AcceleratorName = "radeon-pro-v520"
	AcceleratorName_t4              AcceleratorName = "t4"
	AcceleratorName_v100            AcceleratorName = "v100"
	AcceleratorName_vu9p            AcceleratorName = "vu9p"
)

type AcceleratorType string

const (
	AcceleratorType_fpga      AcceleratorType = "fpga"
	AcceleratorType_gpu       AcceleratorType = "gpu"
	AcceleratorType_inference AcceleratorType = "inference"
)

type BareMetal string

const (
	BareMetal_excluded BareMetal = "excluded"
	BareMetal_included BareMetal = "included"
	BareMetal_required BareMetal = "required"
)

type BurstablePerformance string

const (
	BurstablePerformance_excluded BurstablePerformance = "excluded"
	BurstablePerformance_included BurstablePerformance = "included"
	BurstablePerformance_required BurstablePerformance = "required"
)

type CPUManufacturer string

const (
	CPUManufacturer_amazon_web_services CPUManufacturer = "amazon-web-services"
	CPUManufacturer_amd                 CPUManufacturer = "amd"
	CPUManufacturer_intel               CPUManufacturer = "intel"
)

type CapacityDistributionStrategy string

const (
	CapacityDistributionStrategy_balanced_best_effort CapacityDistributionStrategy = "balanced-best-effort"
	CapacityDistributionStrategy_balanced_only        CapacityDistributionStrategy = "balanced-only"
)

type CapacityReservationPreference string

const (
	CapacityReservationPreference_capacity_reservations_first CapacityReservationPreference = "capacity-reservations-first"
	CapacityReservationPreference_capacity_reservations_only  CapacityReservationPreference = "capacity-reservations-only"
	CapacityReservationPreference_default                     CapacityReservationPreference = "default"
	CapacityReservationPreference_none                        CapacityReservationPreference = "none"
)

type ImpairedZoneHealthCheckBehavior string

const (
	ImpairedZoneHealthCheckBehavior_IgnoreUnhealthy  ImpairedZoneHealthCheckBehavior = "IgnoreUnhealthy"
	ImpairedZoneHealthCheckBehavior_ReplaceUnhealthy ImpairedZoneHealthCheckBehavior = "ReplaceUnhealthy"
)

type InstanceGeneration string

const (
	InstanceGeneration_current  InstanceGeneration = "current"
	InstanceGeneration_previous InstanceGeneration = "previous"
)

type InstanceMetadataEndpointState string

const (
	InstanceMetadataEndpointState_disabled InstanceMetadataEndpointState = "disabled"
	InstanceMetadataEndpointState_enabled  InstanceMetadataEndpointState = "enabled"
)

type InstanceMetadataHTTPTokensState string

const (
	InstanceMetadataHTTPTokensState_optional InstanceMetadataHTTPTokensState = "optional"
	InstanceMetadataHTTPTokensState_required InstanceMetadataHTTPTokensState = "required"
)

type InstanceRefreshStatus string

const (
	InstanceRefreshStatus_Baking             InstanceRefreshStatus = "Baking"
	InstanceRefreshStatus_Cancelled          InstanceRefreshStatus = "Cancelled"
	InstanceRefreshStatus_Cancelling         InstanceRefreshStatus = "Cancelling"
	InstanceRefreshStatus_Failed             InstanceRefreshStatus = "Failed"
	InstanceRefreshStatus_InProgress         InstanceRefreshStatus = "InProgress"
	InstanceRefreshStatus_Pending            InstanceRefreshStatus = "Pending"
	InstanceRefreshStatus_RollbackFailed     InstanceRefreshStatus = "RollbackFailed"
	InstanceRefreshStatus_RollbackInProgress InstanceRefreshStatus = "RollbackInProgress"
	InstanceRefreshStatus_RollbackSuccessful InstanceRefreshStatus = "RollbackSuccessful"
	InstanceRefreshStatus_Successful         InstanceRefreshStatus = "Successful"
)

type LifecycleState string

const (
	LifecycleState_Detached                   LifecycleState = "Detached"
	LifecycleState_Detaching                  LifecycleState = "Detaching"
	LifecycleState_EnteringStandby            LifecycleState = "EnteringStandby"
	LifecycleState_InService                  LifecycleState = "InService"
	LifecycleState_Pending                    LifecycleState = "Pending"
	LifecycleState_Pending_Proceed            LifecycleState = "Pending:Proceed"
	LifecycleState_Pending_Wait               LifecycleState = "Pending:Wait"
	LifecycleState_Quarantined                LifecycleState = "Quarantined"
	LifecycleState_Standby                    LifecycleState = "Standby"
	LifecycleState_Terminated                 LifecycleState = "Terminated"
	LifecycleState_Terminating                LifecycleState = "Terminating"
	LifecycleState_Terminating_Proceed        LifecycleState = "Terminating:Proceed"
	LifecycleState_Terminating_Wait           LifecycleState = "Terminating:Wait"
	LifecycleState_Warmed_Hibernated          LifecycleState = "Warmed:Hibernated"
	LifecycleState_Warmed_Pending             LifecycleState = "Warmed:Pending"
	LifecycleState_Warmed_Pending_Proceed     LifecycleState = "Warmed:Pending:Proceed"
	LifecycleState_Warmed_Pending_Wait        LifecycleState = "Warmed:Pending:Wait"
	LifecycleState_Warmed_Running             LifecycleState = "Warmed:Running"
	LifecycleState_Warmed_Stopped             LifecycleState = "Warmed:Stopped"
	LifecycleState_Warmed_Terminated          LifecycleState = "Warmed:Terminated"
	LifecycleState_Warmed_Terminating         LifecycleState = "Warmed:Terminating"
	LifecycleState_Warmed_Terminating_Proceed LifecycleState = "Warmed:Terminating:Proceed"
	LifecycleState_Warmed_Terminating_Wait    LifecycleState = "Warmed:Terminating:Wait"
)

type LocalStorage string

const (
	LocalStorage_excluded LocalStorage = "excluded"
	LocalStorage_included LocalStorage = "included"
	LocalStorage_required LocalStorage = "required"
)

type LocalStorageType string

const (
	LocalStorageType_hdd LocalStorageType = "hdd"
	LocalStorageType_ssd LocalStorageType = "ssd"
)

type MetricStatistic string

const (
	MetricStatistic_Average     MetricStatistic = "Average"
	MetricStatistic_Maximum     MetricStatistic = "Maximum"
	MetricStatistic_Minimum     MetricStatistic = "Minimum"
	MetricStatistic_SampleCount MetricStatistic = "SampleCount"
	MetricStatistic_Sum         MetricStatistic = "Sum"
)

type MetricType string

const (
	MetricType_ALBRequestCountPerTarget MetricType = "ALBRequestCountPerTarget"
	MetricType_ASGAverageCPUUtilization MetricType = "ASGAverageCPUUtilization"
	MetricType_ASGAverageNetworkIn      MetricType = "ASGAverageNetworkIn"
	MetricType_ASGAverageNetworkOut     MetricType = "ASGAverageNetworkOut"
)

type PredefinedLoadMetricType string

const (
	PredefinedLoadMetricType_ALBTargetGroupRequestCount PredefinedLoadMetricType = "ALBTargetGroupRequestCount"
	PredefinedLoadMetricType_ASGTotalCPUUtilization     PredefinedLoadMetricType = "ASGTotalCPUUtilization"
	PredefinedLoadMetricType_ASGTotalNetworkIn          PredefinedLoadMetricType = "ASGTotalNetworkIn"
	PredefinedLoadMetricType_ASGTotalNetworkOut         PredefinedLoadMetricType = "ASGTotalNetworkOut"
)

type PredefinedMetricPairType string

const (
	PredefinedMetricPairType_ALBRequestCount   PredefinedMetricPairType = "ALBRequestCount"
	PredefinedMetricPairType_ASGCPUUtilization PredefinedMetricPairType = "ASGCPUUtilization"
	PredefinedMetricPairType_ASGNetworkIn      PredefinedMetricPairType = "ASGNetworkIn"
	PredefinedMetricPairType_ASGNetworkOut     PredefinedMetricPairType = "ASGNetworkOut"
)

type PredefinedScalingMetricType string

const (
	PredefinedScalingMetricType_ALBRequestCountPerTarget PredefinedScalingMetricType = "ALBRequestCountPerTarget"
	PredefinedScalingMetricType_ASGAverageCPUUtilization PredefinedScalingMetricType = "ASGAverageCPUUtilization"
	PredefinedScalingMetricType_ASGAverageNetworkIn      PredefinedScalingMetricType = "ASGAverageNetworkIn"
	PredefinedScalingMetricType_ASGAverageNetworkOut     PredefinedScalingMetricType = "ASGAverageNetworkOut"
)

type PredictiveScalingMaxCapacityBreachBehavior string

const (
	PredictiveScalingMaxCapacityBreachBehavior_HonorMaxCapacity    PredictiveScalingMaxCapacityBreachBehavior = "HonorMaxCapacity"
	PredictiveScalingMaxCapacityBreachBehavior_IncreaseMaxCapacity PredictiveScalingMaxCapacityBreachBehavior = "IncreaseMaxCapacity"
)

type PredictiveScalingMode string

const (
	PredictiveScalingMode_ForecastAndScale PredictiveScalingMode = "ForecastAndScale"
	PredictiveScalingMode_ForecastOnly     PredictiveScalingMode = "ForecastOnly"
)

type RefreshStrategy string

const (
	RefreshStrategy_Rolling RefreshStrategy = "Rolling"
)

type ScaleInProtectedInstances string

const (
	ScaleInProtectedInstances_Ignore  ScaleInProtectedInstances = "Ignore"
	ScaleInProtectedInstances_Refresh ScaleInProtectedInstances = "Refresh"
	ScaleInProtectedInstances_Wait    ScaleInProtectedInstances = "Wait"
)

type ScalingActivityStatusCode string

const (
	ScalingActivityStatusCode_Cancelled                       ScalingActivityStatusCode = "Cancelled"
	ScalingActivityStatusCode_Failed                          ScalingActivityStatusCode = "Failed"
	ScalingActivityStatusCode_InProgress                      ScalingActivityStatusCode = "InProgress"
	ScalingActivityStatusCode_MidLifecycleAction              ScalingActivityStatusCode = "MidLifecycleAction"
	ScalingActivityStatusCode_PendingSpotBidPlacement         ScalingActivityStatusCode = "PendingSpotBidPlacement"
	ScalingActivityStatusCode_PreInService                    ScalingActivityStatusCode = "PreInService"
	ScalingActivityStatusCode_Successful                      ScalingActivityStatusCode = "Successful"
	ScalingActivityStatusCode_WaitingForConnectionDraining    ScalingActivityStatusCode = "WaitingForConnectionDraining"
	ScalingActivityStatusCode_WaitingForELBConnectionDraining ScalingActivityStatusCode = "WaitingForELBConnectionDraining"
	ScalingActivityStatusCode_WaitingForInstanceId            ScalingActivityStatusCode = "WaitingForInstanceId"
	ScalingActivityStatusCode_WaitingForInstanceWarmup        ScalingActivityStatusCode = "WaitingForInstanceWarmup"
	ScalingActivityStatusCode_WaitingForSpotInstanceId        ScalingActivityStatusCode = "WaitingForSpotInstanceId"
	ScalingActivityStatusCode_WaitingForSpotInstanceRequestId ScalingActivityStatusCode = "WaitingForSpotInstanceRequestId"
)

type StandbyInstances string

const (
	StandbyInstances_Ignore    StandbyInstances = "Ignore"
	StandbyInstances_Terminate StandbyInstances = "Terminate"
	StandbyInstances_Wait      StandbyInstances = "Wait"
)

type WarmPoolState string

const (
	WarmPoolState_Hibernated WarmPoolState = "Hibernated"
	WarmPoolState_Running    WarmPoolState = "Running"
	WarmPoolState_Stopped    WarmPoolState = "Stopped"
)

type WarmPoolStatus string

const (
	WarmPoolStatus_PendingDelete WarmPoolStatus = "PendingDelete"
)
